brew "mas"
brew "ffmpeg"
cask "charles"
cask "deepl"
cask "figma"
cask "fork"
cask "hammerspoon"
cask "postman"
cask "sublime-text"
cask "visual-studio-code"
cask "warp"
cask "obs"
mas "Ethernet Menu",id: 1549412235
